import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/config/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        page: "var(--color-bg-page)",
        card: "var(--color-bg-card)",
        primary: {
          DEFAULT: "var(--color-primary)",
          hover: "var(--color-primary-hover)",
          soft: "var(--color-primary-soft)",
          deep: "var(--color-primary-deep)",
          navy: "var(--color-primary-navy)",
        },
        cyan: {
          DEFAULT: "var(--color-cyan)",
          soft: "var(--color-cyan-soft)",
        },
        ai: {
          DEFAULT: "var(--color-ai-purple)",
          secondary: "var(--color-ai-purple-2)",
          soft: "var(--color-ai-soft)",
          border: "var(--color-ai-border)",
        },
        success: {
          DEFAULT: "var(--color-success)",
          soft: "var(--color-success-soft)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          soft: "var(--color-warning-soft)",
        },
        danger: {
          DEFAULT: "var(--color-danger)",
          soft: "var(--color-danger-soft)",
        },
        borderSoft: "var(--color-border-soft)",
        borderStrong: "var(--color-border-strong)",
        textMain: "var(--color-text-main)",
        textSecondary: "var(--color-text-secondary)",
        textMuted: "var(--color-text-muted)",
        app: {
          nav: "var(--app-nav-bg)",
          "nav-strong": "var(--app-nav-bg-strong)",
          "nav-soft": "var(--app-nav-bg-soft)",
          page: "var(--app-page-bg)",
          card: "var(--app-card-bg)",
          border: "var(--app-border)",
          primary: "var(--app-primary)",
          "primary-light": "var(--app-primary-light)",
          cyan: "var(--app-cyan)",
          success: "var(--app-success)",
          warning: "var(--app-warning)",
          danger: "var(--app-danger)",
          ai: "var(--app-ai-purple)",
          risk: "var(--app-risk-orange)",
          text: "var(--app-text-primary)",
          muted: "var(--app-text-secondary)",
          inverse: "var(--app-text-inverse)",
        },
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        card: "var(--radius-card)",
        "card-lg": "var(--radius-card-lg)",
        pill: "var(--radius-pill)",
        app: "var(--app-card-radius)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        panel: "var(--shadow-panel)",
        ai: "var(--shadow-ai)",
        topbar: "var(--shadow-topbar)",
        sidebar: "var(--shadow-sidebar)",
        app: "var(--app-shadow-card)",
      },
      spacing: {
        sidebar: "var(--app-sidebar-width)",
        topbar: "var(--app-topbar-height)",
        page: "var(--app-page-padding)",
        "page-gap": "var(--spacing-page-gap)",
        "section-gap": "var(--spacing-section-gap)",
        "card-gap": "var(--spacing-card-gap)",
        "toolbar-gap": "var(--spacing-toolbar-gap)",
        "sidebar-item": "var(--size-sidebar-item-height)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
      },
      fontSize: {
        "page-title": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "page-subtitle": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "section-title": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "card-title": ["15px", { lineHeight: "22px", fontWeight: "600" }],
        body: ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "22px", fontWeight: "500" }],
        table: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "table-header": ["12px", { lineHeight: "18px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "metric-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "metric-md": ["22px", { lineHeight: "30px", fontWeight: "700" }],
        "metric-sm": ["18px", { lineHeight: "26px", fontWeight: "700" }],
      },
    },
  },
};

export default config;
